import json
import os
import sys
import subprocess

def run_command(cmd):
    """Run a shell command and return output."""
    try:
        result = subprocess.run(cmd, shell=True, check=True, capture_output=True, text=True)
        return result.stdout
    except subprocess.CalledProcessError as e:
        print(f"Error running command: {cmd}")
        print(e.stderr)
        sys.exit(1)

def main():
    # 1. Run cargo llvm-cov to get JSON report
    print("Running cargo llvm-cov...")
    run_command("cargo llvm-cov --workspace --exclude ship --json --output-path lcov.json")

    # 2. Parse JSON
    with open("lcov.json", "r") as f:
        data = json.load(f)

    file_coverage = data["data"][0]["files"]
    
    # 3. Define Components (Flags)
    components = {
        "Project": {"patterns": [""], "hits": 0, "lines": 0}, # Global
        "Core": {"patterns": ["crates/core/"], "hits": 0, "lines": 0},
        "Hotpath": {"patterns": ["crates/hotpath/"], "hits": 0, "lines": 0},
        "CLI": {"patterns": ["crates/cli/"], "hits": 0, "lines": 0},
        "Bindings": {"patterns": ["bindings/"], "hits": 0, "lines": 0},
    }

    # 4. Bucketing
    for file in file_coverage:
        filename = file["filename"]
        # In lcov.json, executed_lines is a list of lines. 
        # But for simple summary, we can rely on summary stats if available, 
        # or count lines. llvm-cov json 'files' structure:
        # "summary": { "lines": { "count": 100, "covered": 80, ... } }
        
        summary = file["summary"]["lines"]
        covered = summary["covered"]
        count = summary["count"]

        # Add to matching components
        for name, comp in components.items():
            # "Project" matches everything (empty pattern)
            # Others match prefix
            if any(p in filename for p in comp["patterns"]):
                comp["hits"] += covered
                comp["lines"] += count

    # 5. Calculate & Output
    print(f"{'Component':<15} | {'Coverage':<10} | {'Lines':<10}")
    print("-" * 40)
    
    badges = {}
    
    for name, comp in components.items():
        if comp["lines"] == 0:
            pct = 0.0
        else:
            pct = (comp["hits"] / comp["lines"]) * 100.0
        
        comp["percent"] = pct
        print(f"{name:<15} | {pct:>9.2f}% | {comp['lines']:>10}")

        # Generate Badge JSON (Shields.io schema)
        # Color scale
        if pct > 90:
            color = "brightgreen"
        elif pct > 80:
            color = "green"
        elif pct > 70:
            color = "yellow"
        elif pct > 60:
            color = "orange"
        else:
            color = "red"
        
        badges[name] = {
            "schemaVersion": 1,
            "label": name.lower(),
            "message": f"{pct:.1f}%",
            "color": color
        }

    # 6. Write Badge JSONs
    os.makedirs("badges", exist_ok=True)
    for name, data in badges.items():
        with open(f"badges/{name.lower()}.json", "w") as f:
            json.dump(data, f)
            
    # 7. Write Markdown Summary (for GHA step summary / PR comment)
    with open("coverage_summary.md", "w") as f:
        f.write("### 🛡️ ArqonHPO Coverage Report\n\n")
        f.write("| Component | Coverage | Status |\n")
        f.write("|-----------|----------|--------|\n")
        for name, comp in components.items():
            pct = comp['percent']
            icon = "🟢" if pct > 90 else "🟡" if pct > 70 else "🔴"
            f.write(f"| **{name}** | **{pct:.2f}%** | {icon} |\n")
        f.write("\n_Generated by ArqonHPO Custom Coverage Action_")

if __name__ == "__main__":
    main()
