#!/bin/bash
set -e

HOOK_DIR=".git/hooks"
PRE_COMMIT="$HOOK_DIR/pre-commit"

# Ensure hooks directory exists
if [ ! -d "$HOOK_DIR" ]; then
    echo "Creating .git/hooks directory..."
    mkdir -p "$HOOK_DIR"
fi

echo "Installing pre-commit hook to $PRE_COMMIT..."

# Backup existing hook if it exists
if [ -f "$PRE_COMMIT" ]; then
    echo "Backing up existing pre-commit hook..."
    mv "$PRE_COMMIT" "$PRE_COMMIT.bak"
fi

# Write the hook
cat > "$PRE_COMMIT" << 'EOF'
#!/bin/bash
# Auto-generated by Arqon CI Automation
# Checks code before commit to prevent CI failures.

print_step() {
    echo -e "\033[1;34m==> $1\033[0m"
}

print_error() {
    echo -e "\033[1;31m❌ $1\033[0m"
}

export PATH="$HOME/.cargo/bin:$PATH"

# 1. Format Check
print_step "Checking formatting..."
if ! cargo fmt --all -- --check; then
    print_error "Formatting failed. Run 'cargo fmt --all' locally to fix."
    exit 1
fi

# 2. Compilation Check
print_step "Checking compilation (cargo check)..."
if ! cargo check --workspace; then
    print_error "Compilation failed. Please fix errors before committing."
    exit 1
fi

# 3. Fast Unit Tests
# Excluding 'ship' crate tests for speed if they are integration heavy.
# Uncomment next line to enable:
# print_step "Running fast unit tests..."
# if ! cargo test --workspace --lib --exclude ship; then
#     print_error "Unit tests failed."
#     exit 1
# fi

echo -e "\033[1;32m✅ Pre-commit checks passed! Commit allowed.\033[0m"
exit 0
EOF

chmod +x "$PRE_COMMIT"
echo "✅ Pre-commit hook installed successfully! Future commits will be verified locally."
